apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-jixx-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:81d828d1f9e3dda1cd710489aa96f43a6aa28a8a3d384d4868652d8f30ab7261
        name: container-image
        resources: {}
status: {}
